# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-11-19 04:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepg', '0004_auto_20211117_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='insert',
            name='image',
            field=models.ImageField(null=True, upload_to=b'images'),
        ),
    ]
